In [2]:
print("merhaba")

merhaba

# Ege Bölgesi için bir kira tahmin uygulaması

In [3]:
import os 
import pandas as pd
import numpy as np

In [4]:
# Veri temizleme işlemleri için gerekli fonksiyon
def drop_columns(df, cols):
    '''
    Belirtilen sütunları DataFrame'den siler.
    '''
    for col in cols:
        try:
            df.drop( col,axis=1, inplace=True) # belirtilen sütunları siler
        except Exception as e:
            print(f"Hata: {e}") # hata mesajını yazdırır

In [5]:
help(pd.read_csv) # help fonksiyonu ile pd.read_csv fonksiyonunun ne işe yaradığını öğrenebiliriz

Help on function read_csv in module pandas.io.parsers.readers:

read_csv(
    filepath_or_buffer: 'FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str]',
    *,
    sep: 'str | None | lib.NoDefault' = <no_default>,
    delimiter: 'str | None | lib.NoDefault' = None,
    header: "int | Sequence[int] | None | Literal['infer']" = 'infer',
    names: 'Sequence[Hashable] | None | lib.NoDefault' = <no_default>,
    index_col: 'IndexLabel | Literal[False] | None' = None,
    usecols: 'UsecolsArgType' = None,
    dtype: 'DtypeArg | None' = None,
    engine: 'CSVEngine | None' = None,
    converters: 'Mapping[Hashable, Callable] | None' = None,
    true_values: 'list | None' = None,
    false_values: 'list | None' = None,
    skipinitialspace: 'bool' = False,
    skiprows: 'list[int] | int | Callable[[Hashable], bool] | None' = None,
    skipfooter: 'int' = 0,
    nrows: 'int | None' = None,
    na_values: 'Hashable | Iterable[Hashable] | Mapping[Hashable, Iterable[Hashable]] | None' = None,
    keep_default_na: 'bool' = True,
    na_filter: 'bool' = True,
    verbose: 'bool | lib.NoDefault' = <no_default>,
    skip_blank_lines: 'bool' = True,
    parse_dates: 'bool | Sequence[Hashable] | None' = None,
    infer_datetime_format: 'bool | lib.NoDefault' = <no_default>,
    keep_date_col: 'bool | lib.NoDefault' = <no_default>,
    date_parser: 'Callable | lib.NoDefault' = <no_default>,
    date_format: 'str | dict[Hashable, str] | None' = None,
    dayfirst: 'bool' = False,
    cache_dates: 'bool' = True,
    iterator: 'bool' = False,
    chunksize: 'int | None' = None,
    compression: 'CompressionOptions' = 'infer',
    thousands: 'str | None' = None,
    decimal: 'str' = '.',
    lineterminator: 'str | None' = None,
    quotechar: 'str' = '"',
    quoting: 'int' = 0,
    doublequote: 'bool' = True,
    escapechar: 'str | None' = None,
    comment: 'str | None' = None,
    encoding: 'str | None' = None,
    encoding_errors: 'str | None' = 'strict',
    dialect: 'str | csv.Dialect | None' = None,
    on_bad_lines: 'str' = 'error',
    delim_whitespace: 'bool | lib.NoDefault' = <no_default>,
    low_memory: 'bool' = True,
    memory_map: 'bool' = False,
    float_precision: "Literal['high', 'legacy'] | None" = None,
    storage_options: 'StorageOptions | None' = None,
    dtype_backend: 'DtypeBackend | lib.NoDefault' = <no_default>
) -> 'DataFrame | TextFileReader'
    Read a comma-separated values (csv) file into DataFrame.

    Also supports optionally iterating or breaking of the file
    into chunks.

    Additional help can be found in the online docs for
    `IO Tools <https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html>`_.

    Parameters
    ----------
    filepath_or_buffer : str, path object or file-like object
        Any valid string path is acceptable. The string could be a URL. Valid
        URL schemes include http, ftp, s3, gs, and file. For file URLs, a host is
        expected. A local file could be: file://localhost/path/to/table.csv.

        If you want to pass in a path object, pandas accepts any ``os.PathLike``.

        By file-like object, we refer to objects with a ``read()`` method, such as
        a file handle (e.g. via builtin ``open`` function) or ``StringIO``.
    sep : str, default ','
        Character or regex pattern to treat as the delimiter. If ``sep=None``, the
        C engine cannot automatically detect
        the separator, but the Python parsing engine can, meaning the latter will
        be used and automatically detect the separator from only the first valid
        row of the file by Python's builtin sniffer tool, ``csv.Sniffer``.
        In addition, separators longer than 1 character and different from
        ``'\s+'`` will be interpreted as regular expressions and will also force
        the use of the Python parsing engine. Note that regex delimiters are prone
        to ignoring quoted data. Regex example: ``'\r\t'``.
    delimiter : str, optional
        Alias for ``sep``.
    header : int, Sequence of int, 'infer' or None, default 'infer'
        Row number(s) containing column labels and marking the start of the
        data (zero-indexed). Default behavior is to infer the column names: if no ``names``
        are passed the behavior is identical to ``header=0`` and column
        names are inferred from the first line of the file, if column
        names are passed explicitly to ``names`` then the behavior is identical to
        ``header=None``. Explicitly pass ``header=0`` to be able to
        replace existing names. The header can be a list of integers that
        specify row locations for a :class:`~pandas.MultiIndex` on the columns
        e.g. ``[0, 1, 3]``. Intervening rows that are not specified will be
        skipped (e.g. 2 in this example is skipped). Note that this
        parameter ignores commented lines and empty lines if
        ``skip_blank_lines=True``, so ``header=0`` denotes the first line of
        data rather than the first line of the file.
    names : Sequence of Hashable, optional
        Sequence of column labels to apply. If the file contains a header row,
        then you should explicitly pass ``header=0`` to override the column names.
        Duplicates in this list are not allowed.
    index_col : Hashable, Sequence of Hashable or False, optional
      Column(s) to use as row label(s), denoted either by column labels or column
      indices.  If a sequence of labels or indices is given, :class:`~pandas.MultiIndex`
      will be formed for the row labels.

      Note: ``index_col=False`` can be used to force pandas to *not* use the first
      column as the index, e.g., when you have a malformed file with delimiters at
      the end of each line.
    usecols : Sequence of Hashable or Callable, optional
        Subset of columns to select, denoted either by column labels or column indices.
        If list-like, all elements must either
        be positional (i.e. integer indices into the document columns) or strings
        that correspond to column names provided either by the user in ``names`` or
        inferred from the document header row(s). If ``names`` are given, the document
        header row(s) are not taken into account. For example, a valid list-like
        ``usecols`` parameter would be ``[0, 1, 2]`` or ``['foo', 'bar', 'baz']``.
        Element order is ignored, so ``usecols=[0, 1]`` is the same as ``[1, 0]``.
        To instantiate a :class:`~pandas.DataFrame` from ``data`` with element order
        preserved use ``pd.read_csv(data, usecols=['foo', 'bar'])[['foo', 'bar']]``
        for columns in ``['foo', 'bar']`` order or
        ``pd.read_csv(data, usecols=['foo', 'bar'])[['bar', 'foo']]``
        for ``['bar', 'foo']`` order.

        If callable, the callable function will be evaluated against the column
        names, returning names where the callable function evaluates to ``True``. An
        example of a valid callable argument would be ``lambda x: x.upper() in
        ['AAA', 'BBB', 'DDD']``. Using this parameter results in much faster
        parsing time and lower memory usage.
    dtype : dtype or dict of {Hashable : dtype}, optional
        Data type(s) to apply to either the whole dataset or individual columns.
        E.g., ``{'a': np.float64, 'b': np.int32, 'c': 'Int64'}``
        Use ``str`` or ``object`` together with suitable ``na_values`` settings
        to preserve and not interpret ``dtype``.
        If ``converters`` are specified, they will be applied INSTEAD
        of ``dtype`` conversion.

        .. versionadded:: 1.5.0

            Support for ``defaultdict`` was added. Specify a ``defaultdict`` as input where
            the default determines the ``dtype`` of the columns which are not explicitly
            listed.
    engine : {'c', 'python', 'pyarrow'}, optional
        Parser engine to use. The C and pyarrow engines are faster, while the python engine
        is currently more feature-complete. Multithreading is currently only supported by
        the pyarrow engine.

        .. versionadded:: 1.4.0

            The 'pyarrow' engine was added as an *experimental* engine, and some features
            are unsupported, or may not work correctly, with this engine.
    converters : dict of {Hashable : Callable}, optional
        Functions for converting values in specified columns. Keys can either
        be column labels or column indices.
    true_values : list, optional
        Values to consider as ``True`` in addition to case-insensitive variants of 'True'.
    false_values : list, optional
        Values to consider as ``False`` in addition to case-insensitive variants of 'False'.
    skipinitialspace : bool, default False
        Skip spaces after delimiter.
    skiprows : int, list of int or Callable, optional
        Line numbers to skip (0-indexed) or number of lines to skip (``int``)
        at the start of the file.

        If callable, the callable function will be evaluated against the row
        indices, returning ``True`` if the row should be skipped and ``False`` otherwise.
        An example of a valid callable argument would be ``lambda x: x in [0, 2]``.
    skipfooter : int, default 0
        Number of lines at bottom of file to skip (Unsupported with ``engine='c'``).
    nrows : int, optional
        Number of rows of file to read. Useful for reading pieces of large files.
    na_values : Hashable, Iterable of Hashable or dict of {Hashable : Iterable}, optional
        Additional strings to recognize as ``NA``/``NaN``. If ``dict`` passed, specific
        per-column ``NA`` values.  By default the following values are interpreted as
        ``NaN``: " ", "#N/A", "#N/A N/A", "#NA", "-1.#IND", "-1.#QNAN", "-NaN", "-nan",
        "1.#IND", "1.#QNAN", "<NA>", "N/A", "NA", "NULL", "NaN", "None",
        "n/a", "nan", "null ".

    keep_default_na : bool, default True
        Whether or not to include the default ``NaN`` values when parsing the data.
        Depending on whether ``na_values`` is passed in, the behavior is as follows:

        * If ``keep_default_na`` is ``True``, and ``na_values`` are specified, ``na_values``
          is appended to the default ``NaN`` values used for parsing.
        * If ``keep_default_na`` is ``True``, and ``na_values`` are not specified, only
          the default ``NaN`` values are used for parsing.
        * If ``keep_default_na`` is ``False``, and ``na_values`` are specified, only
          the ``NaN`` values specified ``na_values`` are used for parsing.
        * If ``keep_default_na`` is ``False``, and ``na_values`` are not specified, no
          strings will be parsed as ``NaN``.

        Note that if ``na_filter`` is passed in as ``False``, the ``keep_default_na`` and
        ``na_values`` parameters will be ignored.
    na_filter : bool, default True
        Detect missing value markers (empty strings and the value of ``na_values``). In
        data without any ``NA`` values, passing ``na_filter=False`` can improve the
        performance of reading a large file.
    verbose : bool, default False
        Indicate number of ``NA`` values placed in non-numeric columns.

        .. deprecated:: 2.2.0
    skip_blank_lines : bool, default True
        If ``True``, skip over blank lines rather than interpreting as ``NaN`` values.
    parse_dates : bool, list of Hashable, list of lists or dict of {Hashable : list}, default False
        The behavior is as follows:

        * ``bool``. If ``True`` -> try parsing the index. Note: Automatically set to
          ``True`` if ``date_format`` or ``date_parser`` arguments have been passed.
        * ``list`` of ``int`` or names. e.g. If ``[1, 2, 3]`` -> try parsing columns 1, 2, 3
          each as a separate date column.
        * ``list`` of ``list``. e.g.  If ``[[1, 3]]`` -> combine columns 1 and 3 and parse
          as a single date column. Values are joined with a space before parsing.
        * ``dict``, e.g. ``{'foo' : [1, 3]}`` -> parse columns 1, 3 as date and call
          result 'foo'. Values are joined with a space before parsing.

        If a column or index cannot be represented as an array of ``datetime``,
        say because of an unparsable value or a mixture of timezones, the column
        or index will be returned unaltered as an ``object`` data type. For
        non-standard ``datetime`` parsing, use :func:`~pandas.to_datetime` after
        :func:`~pandas.read_csv`.

        Note: A fast-path exists for iso8601-formatted dates.
    infer_datetime_format : bool, default False
        If ``True`` and ``parse_dates`` is enabled, pandas will attempt to infer the
        format of the ``datetime`` strings in the columns, and if it can be inferred,
        switch to a faster method of parsing them. In some cases this can increase
        the parsing speed by 5-10x.

        .. deprecated:: 2.0.0
            A strict version of this argument is now the default, passing it has no effect.

    keep_date_col : bool, default False
        If ``True`` and ``parse_dates`` specifies combining multiple columns then
        keep the original columns.
    date_parser : Callable, optional
        Function to use for converting a sequence of string columns to an array of
        ``datetime`` instances. The default uses ``dateutil.parser.parser`` to do the
        conversion. pandas will try to call ``date_parser`` in three different ways,
        advancing to the next if an exception occurs: 1) Pass one or more arrays
        (as defined by ``parse_dates``) as arguments; 2) concatenate (row-wise) the
        string values from the columns defined by ``parse_dates`` into a single array
        and pass that; and 3) call ``date_parser`` once for each row using one or
        more strings (corresponding to the columns defined by ``parse_dates``) as
        arguments.

        .. deprecated:: 2.0.0
           Use ``date_format`` instead, or read in as ``object`` and then apply
           :func:`~pandas.to_datetime` as-needed.
    date_format : str or dict of column -> format, optional
        Format to use for parsing dates when used in conjunction with ``parse_dates``.
        The strftime to parse time, e.g. :const:`"%d/%m/%Y"`. See
        `strftime documentation
        <https://docs.python.org/3/library/datetime.html
        #strftime-and-strptime-behavior>`_ for more information on choices, though
        note that :const:`"%f"` will parse all the way up to nanoseconds.
        You can also pass:

        - "ISO8601", to parse any `ISO8601 <https://en.wikipedia.org/wiki/ISO_8601>`_
            time string (not necessarily in exactly the same format);
        - "mixed", to infer the format for each element individually. This is risky,
            and you should probably use it along with `dayfirst`.

        .. versionadded:: 2.0.0
    dayfirst : bool, default False
        DD/MM format dates, international and European format.
    cache_dates : bool, default True
        If ``True``, use a cache of unique, converted dates to apply the ``datetime``
        conversion. May produce significant speed-up when parsing duplicate
        date strings, especially ones with timezone offsets.

    iterator : bool, default False
        Return ``TextFileReader`` object for iteration or getting chunks with
        ``get_chunk()``.
    chunksize : int, optional
        Number of lines to read from the file per chunk. Passing a value will cause the
        function to return a ``TextFileReader`` object for iteration.
        See the `IO Tools docs
        <https://pandas.pydata.org/pandas-docs/stable/io.html#io-chunking>`_
        for more information on ``iterator`` and ``chunksize``.

    compression : str or dict, default 'infer'
        For on-the-fly decompression of on-disk data. If 'infer' and 'filepath_or_buffer' is
        path-like, then detect compression from the following extensions: '.gz',
        '.bz2', '.zip', '.xz', '.zst', '.tar', '.tar.gz', '.tar.xz' or '.tar.bz2'
        (otherwise no compression).
        If using 'zip' or 'tar', the ZIP file must contain only one data file to be read in.
        Set to ``None`` for no decompression.
        Can also be a dict with key ``'method'`` set
        to one of {``'zip'``, ``'gzip'``, ``'bz2'``, ``'zstd'``, ``'xz'``, ``'tar'``} and
        other key-value pairs are forwarded to
        ``zipfile.ZipFile``, ``gzip.GzipFile``,
        ``bz2.BZ2File``, ``zstandard.ZstdDecompressor``, ``lzma.LZMAFile`` or
        ``tarfile.TarFile``, respectively.
        As an example, the following could be passed for Zstandard decompression using a
        custom compression dictionary:
        ``compression={'method': 'zstd', 'dict_data': my_compression_dict}``.

        .. versionadded:: 1.5.0
            Added support for `.tar` files.

        .. versionchanged:: 1.4.0 Zstandard support.

    thousands : str (length 1), optional
        Character acting as the thousands separator in numerical values.
    decimal : str (length 1), default '.'
        Character to recognize as decimal point (e.g., use ',' for European data).
    lineterminator : str (length 1), optional
        Character used to denote a line break. Only valid with C parser.
    quotechar : str (length 1), optional
        Character used to denote the start and end of a quoted item. Quoted
        items can include the ``delimiter`` and it will be ignored.
    quoting : {0 or csv.QUOTE_MINIMAL, 1 or csv.QUOTE_ALL, 2 or csv.QUOTE_NONNUMERIC, 3 or csv.QUOTE_NONE}, default csv.QUOTE_MINIMAL
        Control field quoting behavior per ``csv.QUOTE_*`` constants. Default is
        ``csv.QUOTE_MINIMAL`` (i.e., 0) which implies that only fields containing special
        characters are quoted (e.g., characters defined in ``quotechar``, ``delimiter``,
        or ``lineterminator``.
    doublequote : bool, default True
       When ``quotechar`` is specified and ``quoting`` is not ``QUOTE_NONE``, indicate
       whether or not to interpret two consecutive ``quotechar`` elements INSIDE a
       field as a single ``quotechar`` element.
    escapechar : str (length 1), optional
        Character used to escape other characters.
    comment : str (length 1), optional
        Character indicating that the remainder of line should not be parsed.
        If found at the beginning
        of a line, the line will be ignored altogether. This parameter must be a
        single character. Like empty lines (as long as ``skip_blank_lines=True``),
        fully commented lines are ignored by the parameter ``header`` but not by
        ``skiprows``. For example, if ``comment='#'``, parsing
        ``#empty\na,b,c\n1,2,3`` with ``header=0`` will result in ``'a,b,c'`` being
        treated as the header.
    encoding : str, optional, default 'utf-8'
        Encoding to use for UTF when reading/writing (ex. ``'utf-8'``). `List of Python
        standard encodings
        <https://docs.python.org/3/library/codecs.html#standard-encodings>`_ .

    encoding_errors : str, optional, default 'strict'
        How encoding errors are treated. `List of possible values
        <https://docs.python.org/3/library/codecs.html#error-handlers>`_ .

        .. versionadded:: 1.3.0

    dialect : str or csv.Dialect, optional
        If provided, this parameter will override values (default or not) for the
        following parameters: ``delimiter``, ``doublequote``, ``escapechar``,
        ``skipinitialspace``, ``quotechar``, and ``quoting``. If it is necessary to
        override values, a ``ParserWarning`` will be issued. See ``csv.Dialect``
        documentation for more details.
    on_bad_lines : {'error', 'warn', 'skip'} or Callable, default 'error'
        Specifies what to do upon encountering a bad line (a line with too many fields).
        Allowed values are :

        - ``'error'``, raise an Exception when a bad line is encountered.

In [6]:
df = pd.read_csv('hepsiemlak.csv')

In [7]:
print(df)

                                          img-link href  photo-count  \
0     https://www.hepsiemlak.com/ankara-mamak-genera...         12.0
1     https://www.hepsiemlak.com/istanbul-beylikduzu...         36.0
2     https://www.hepsiemlak.com/antalya-kepez-selal...         13.0
3     https://www.hepsiemlak.com/istanbul-kucukcekme...         39.0
4     https://www.hepsiemlak.com/ankara-altindag-ayd...         17.0
...                                                 ...          ...
9447  https://www.hepsiemlak.com/mersin-tarsus-sehit...         29.0
9448  https://www.hepsiemlak.com/gaziantep-sahinbey-...          9.0
9449  https://www.hepsiemlak.com/adana-seyhan-namik-...          9.0
9450  https://www.hepsiemlak.com/izmir-dikili-ismetp...          9.0
9451  https://www.hepsiemlak.com/konya-eregli-orhani...         21.0

     list-view-price currency list-view-date                 left  \
0             20.000       TL     30-07-2025        Kiralık Daire
1             29.250       TL     30-07-2025        Kiralık Daire
2             20.000       TL     29-07-2025        Kiralık Daire
3             50.000       TL     30-07-2025        Kiralık Daire
4             20.000       TL     30-07-2025        Kiralık Daire
...              ...      ...            ...                  ...
9447          40.000       TL     02-07-2025        Kiralık Daire
9448          17.000       TL     30-07-2025        Kiralık Daire
9449          10.000       TL     29-07-2025  Kiralık Müstakil Ev
9450          20.000       TL     28-07-2025        Kiralık Daire
9451           7.500       TL     29-07-2025        Kiralık Daire

                                   celly celly 2  \
0     2 +\r\n                          1  100 m²
1     1 +\r\n                          1   80 m²
2     2 +\r\n                          1  100 m²
3     2 +\r\n                          1  135 m²
4     3 +\r\n                          1  130 m²
...                                  ...     ...
9447  2 +\r\n                          1  115 m²
9448  2 +\r\n                          1   80 m²
9449  2 +\r\n                          1  110 m²
9450  1 +\r\n                          1   75 m²
9451  2 +\r\n                          1  120 m²

                                    celly 3       celly 4  \
0     25\r\n                        Yaşında  Yüksek Giriş
1                                Sıfır Bina        8. Kat
2      1\r\n                        Yaşında  Yüksek Giriş
3      4\r\n                        Yaşında       10. Kat
4     40\r\n                        Yaşında        3. Kat
...                                     ...           ...
9447  25\r\n                        Yaşında        3. Kat
9448   8\r\n                        Yaşında        3. Kat
9449  20\r\n                        Yaşında           NaN
9450   1\r\n                        Yaşında        1. Kat
9451                             Sıfır Bina        3. Kat

                             list-view-location  \
0      Ankara / Mamak / General Zeki Doğan Mah.
1       İstanbul / Beylikdüzü / Cumhuriyet Mah.
2                 Antalya / Kepez / Şelale Mah.
3     İstanbul / Küçükçekmece / Cumhuriyet Mah.
4        Ankara / Altındağ / Aydınlıkevler Mah.
...                                         ...
9447        Mersin / Tarsus / Şehitmustafa Mah.
9448   Gaziantep / Şahinbey / Bahçelievler Mah.
9449          Adana / Seyhan / Namık Kemal Mah.
9450            İzmir / Dikili / İsmetpaşa Mah.
9451             Konya / Ereğli / Orhaniye Mah.

                                           img-wrp href  \
0     https://www.hepsiemlak.com/emlak-ofisi/turksoy...
1     https://www.hepsiemlak.com/emlak-ofisi/uzmanla...
2                                                   NaN
3     https://www.hepsiemlak.com/emlak-ofisi/uzmanla...
4     https://www.hepsiemlak.com/emlak-ofisi/ada-eml...
...                                                 ...
9447                                                NaN
9448                                                NaN
9449  https://www.hepsiemlak.com/emlak-ofisi/01-yapi...
9450  https://www.hepsiemlak.com/emlak-ofisi/turpa-a...
9451  https://www.hepsiemlak.com/emlak-ofisi/karaca-...

                                      he-lazy-image src    wp-btn  \
0     https://hecdnnw.hemlak.com/mncropresize/77/67/...  Whatsapp
1     https://hecdnnw.hemlak.com/mncropresize/77/67/...  Whatsapp
2                                                   NaN  Whatsapp
3     https://hecdn01.hemlak.com/mncropresize/280/21...  Whatsapp
4     https://hecdn01.hemlak.com/mncropresize/280/21...  Whatsapp
...                                                 ...       ...
9447  https://hecdn01.hemlak.com/mncropresize/182/13...  Whatsapp
9448  https://hecdn01.hemlak.com/mncropresize/182/13...  Whatsapp
9449  https://hecdn01.hemlak.com/mncropresize/182/13...  Whatsapp
9450  https://hecdn01.hemlak.com/mncropresize/182/13...  Whatsapp
9451  https://hecdn01.hemlak.com/mncropresize/182/13...  Whatsapp

       listing-card--owner-info__firm-name listing-card--owner-info__name  \
0                      Türksoy Gayrimenkul      Filiz\r\n          Öztürk
1                     Uzmanlar Gayrimenkul                            NaN
2                                      NaN                            NaN
3                     Uzmanlar Gayrimenkul                            NaN
4                                Ada Emlak                            NaN
...                                    ...                            ...
9447                                   NaN                            NaN
9448                                   NaN                            NaN
9449                         01 Yapı Emlak                            NaN
9450  Turpa Arxes Gayrimenkul Danışmanlığı                            NaN
9451                          Karaca Emlak                            NaN

                                    he-lazy-image src 2  \
0                                                   NaN
1                                                   NaN
2                                                   NaN
3     https://hecdnnw.hemlak.com/mncropresize/77/67/...
4     https://www.hepsiemlak.com/img/loadings/noImag...
...                                                 ...
9447                                                NaN
9448                                                NaN
9449  https://hecdnnw.hemlak.com/mncropresize/77/67/...
9450  https://hecdnnw.hemlak.com/mncropresize/77/67/...
9451  https://hecdnnw.hemlak.com/mncropresize/77/67/...

                                       list-view-header
0                                                   NaN
1                                                   NaN
2                                                   NaN
3                                                   NaN
4                                                   NaN
...                                                 ...
9447  Tarsus Çarşı Yarenlik Merkezinde İçi Ful Yapıl...
9448               Sng Gyd'den Eşyalı Kiralık 2+1 Daire
9449  Güneş Enerjili, Bakımlı, Merkezi Konumda, Kira...
9450        Turpa Arxes Dikili Den Kiralık Eşyalı Daire
9451             4.Etap Toki Konutları Kiralık 2+1daire

[9452 rows x 18 columns]

In [8]:
dir(df) #df ile ilgili fonksiyonlar

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__arrow_c_stream__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__dataframe__',
 '__dataframe_consortium_standard__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__firstlineno__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pandas_priority__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__static_attributes__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_agg_examples_doc',
 '_agg_see_also_doc',
 '_align_for_op',
 '_align_frame',
 '_align_series',
 '_append',
 '_arith_method',
 '_arith_method_with_reindex',
 '_as_manager',
 '_attrs',
 '_box_col_values',
 '_can_fast_transpose',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_is_chained_assignment_possible',
 '_check_label_or_level_ambiguity',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_combine_frame',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_result',
 '_constructor',
 '_constructor_from_mgr',
 '_constructor_sliced',
 '_constructor_sliced_from_mgr',
 '_create_data_for_split_and_tight_to_dict',
 '_data',
 '_deprecate_downcast',
 '_dir_additions',
 '_dir_deletions',
 '_dispatch_frame_op',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_ensure_valid_index',
 '_find_valid_index',
 '_flags',
 '_flex_arith_method',
 '_flex_cmp_method',
 '_from_arrays',
 '_from_mgr',
 '_get_agg_axis',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cleaned_column_resolvers',
 '_get_column_array',
 '_get_index_resolvers',
 '_get_item_cache',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_get_values_for_csv',
 '_getitem_bool_array',
 '_getitem_multilevel',
 '_getitem_nocopy',
 '_getitem_slice',
 '_gotitem',
 '_hidden_attrs',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_info_repr',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_copy',
 '_is_homogeneous_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_is_view',
 '_is_view_after_cow_rules',
 '_iset_item',
 '_iset_item_mgr',
 '_iset_not_inplace',
 '_item_cache',
 '_iter_column_arrays',
 '_ixs',
 '_logical_func',
 '_logical_method',
 '_maybe_align_series_as_frame',
 '_maybe_cache_changed',
 '_maybe_update_cacher',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_needs_reindex_multi',
 '_pad_or_backfill',
 '_protect_consolidate',
 '_reduce',
 '_reduce_axis1',
 '_reindex_axes',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_rename',
 '_replace_columnwise',
 '_repr_data_resource_',
 '_repr_fits_horizontal_',
 '_repr_fits_vertical_',
 '_repr_html_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_sanitize_column',
 '_series',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_is_copy',
 '_set_item',
 '_set_item_frame_value',
 '_set_item_mgr',
 '_set_value',
 '_setitem_array',
 '_setitem_frame',
 '_setitem_slice',
 '_shift_with_freq',
 '_should_reindex_frame_op',
 '_slice',
 '_stat_function',
 '_stat_function_ddof',
 '_take_with_is_copy',
 '_to_dict_of_blocks',
 '_to_latex_via_styler',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'apply',
 'applymap',
 'asfreq',
 'asof',
 'assign',
 'astype',
 'at',
 'at_time',
 'attrs',
 'axes',
 'backfill',
 'between_time',
 'bfill',
 'bool',
 'boxplot',
 'celly',
 'clip',
 'columns',
 'combine',
 'combine_first',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'corrwith',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'currency',
 'describe',
 'diff',
 'div',
 'divide',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'eval',
 'ewm',
 'expanding',
 'explode',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'flags',
 'floordiv',
 'from_dict',
 'from_records',
 'ge',
 'get',
 'groupby',
 'gt',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'insert',
 'interpolate',
 'isetitem',
 'isin',
 'isna',
 'isnull',
 'items',
 'iterrows',
 'itertuples',
 'join',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'left',
 'loc',
 'lt',
 'map',
 'mask',
 'max',
 'mean',
 'median',
 'melt',
 'memory_usage',
 'merge',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pad',
 'pct_change',
 'pipe',
 'pivot',
 'pivot_table',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'query',
 'radd',
 'rank',
 'rdiv',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'select_dtypes',
 'sem',
 'set_axis',
 'set_flags',
 'set_index',
 'shape',
 'shift',
 'size',
 'skew',
 'sort_index',
 'sort_values',
 'squeeze',
 'stack',
 'std',
 'style',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_gbq',
 'to_hdf',
 'to_html',
 'to_json',
 'to_latex',
 'to_markdown',
 'to_numpy',
 'to_orc',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'to_xml',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'where',
 'xs']

In [9]:
print(df.info()) #df ile ilgili bilgileri verir

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9452 entries, 0 to 9451
Data columns (total 18 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   img-link href                        9452 non-null   object
 1   photo-count                          9448 non-null   float64
 2   list-view-price                      9452 non-null   object
 3   currency                             9452 non-null   object
 4   list-view-date                       9452 non-null   object
 5   left                                 9452 non-null   object
 6   celly                                9452 non-null   object
 7   celly 2                              9452 non-null   object
 8   celly 3                              9452 non-null   object
 9   celly 4                              9070 non-null   object
 10  list-view-location                   9452 non-null   object
 11  img-wrp href                         5283 non-null   object
 12  he-lazy-image src                    8908 non-null   object
 13  wp-btn                               9447 non-null   object
 14  listing-card--owner-info__firm-name  5283 non-null   object
 15  listing-card--owner-info__name       2025 non-null   object
 16  he-lazy-image src 2                  4808 non-null   object
 17  list-view-header                     9411 non-null   object
dtypes: float64(1), object(17)
memory usage: 1.3+ MB
None

In [10]:
# files = os.listdir('KlasorAdi') # klasördeki dosyaları listelemek için kullanılır
#for file in files:
#    print(file) # her bir dosyanın ismini yazdırır

In [11]:
# files = os.listdir('KlasorAdi') # klasördeki dosyaları listelemek için kullanılır,
# df = pd.concat[pd.read_csv(f'KlasörAdi/{file}') for file in files, ignore_index=True] # her bir dosyayı okur ve birleştirir
# for file in sorted(files): # dosyaları alfabetik sıraya göre sıralar
#     df = pd.read_csv(f'KlasörAdi/{file}') # her bir dosyayı okur

In [12]:
# print(df.head()) # ilk 5 satırı gösterir
# print(df.tail()) # son 5 satırı gösterir   
print(df.sample(50))   # rastgele 50 satır gösterir

                                          img-link href  photo-count  \
7198  https://www.hepsiemlak.com/istanbul-sisli-cumh...         22.0
3726  https://www.hepsiemlak.com/antalya-alanya-mahm...         27.0
8257  https://www.hepsiemlak.com/aydin-kusadasi-degi...         49.0
4767  https://www.hepsiemlak.com/aydin-didim-efeler-...         20.0
8961  https://www.hepsiemlak.com/eskisehir-odunpazar...         38.0
8679  https://www.hepsiemlak.com/balikesir-edremit-c...         21.0
5723  https://www.hepsiemlak.com/ankara-mamak-kartal...         10.0
1139  https://www.hepsiemlak.com/ankara-golbasi-tasp...         29.0
3111  https://www.hepsiemlak.com/kocaeli-darica-emek...         29.0
1492  https://www.hepsiemlak.com/antalya-konyaalti-l...         20.0
8651  https://www.hepsiemlak.com/izmir-karsiyaka-bos...         29.0
7648  https://www.hepsiemlak.com/ankara-cankaya-malt...         28.0
5024  https://www.hepsiemlak.com/ankara-cankaya-alac...         30.0
2356  https://www.hepsiemlak.com/zonguldak-merkez-in...         17.0
1609  https://www.hepsiemlak.com/mugla-milas-oren-ki...         18.0
5201  https://www.hepsiemlak.com/istanbul-kadikoy-go...         27.0
4437  https://www.hepsiemlak.com/bursa-osmangazi-pan...         20.0
272   https://www.hepsiemlak.com/ankara-cankaya-birl...         35.0
4621  https://www.hepsiemlak.com/ankara-sincan-gokce...         58.0
9035  https://www.hepsiemlak.com/istanbul-sisli-merk...         60.0
4828  https://www.hepsiemlak.com/istanbul-kucukcekme...         13.0
4612  https://www.hepsiemlak.com/antalya-konyaalti-h...         16.0
970   https://www.hepsiemlak.com/mersin-anamur-iskel...         31.0
2249  https://www.hepsiemlak.com/aydin-efeler-mesrut...         38.0
7699  https://www.hepsiemlak.com/istanbul-gaziosmanp...         15.0
7679  https://www.hepsiemlak.com/eskisehir-odunpazar...         31.0
2285  https://www.hepsiemlak.com/mugla-bodrum-geris-...         25.0
1975  https://www.hepsiemlak.com/istanbul-uskudar-se...         24.0
8044  https://www.hepsiemlak.com/ankara-yenimahalle-...         26.0
9318  https://www.hepsiemlak.com/konya-karapinar-zaf...         10.0
4581  https://www.hepsiemlak.com/izmir-cigli-evka-2-...         25.0
2608  https://www.hepsiemlak.com/adana-cukurova-huzu...         35.0
5848  https://www.hepsiemlak.com/eskisehir-odunpazar...         50.0
2629  https://www.hepsiemlak.com/ankara-kecioren-kar...         55.0
3857  https://www.hepsiemlak.com/izmir-karsiyaka-yal...         35.0
7238  https://www.hepsiemlak.com/ankara-cankaya-naci...         36.0
2737  https://www.hepsiemlak.com/istanbul-besiktas-d...         42.0
8551  https://www.hepsiemlak.com/mersin-mezitli-yeni...         23.0
7696  https://www.hepsiemlak.com/ankara-cankaya-sehi...          7.0
2158  https://www.hepsiemlak.com/hatay-dortyol-yesil...          7.0
6021  https://www.hepsiemlak.com/ankara-polatli-cumh...         27.0
3137  https://www.hepsiemlak.com/izmir-dikili-candar...         12.0
8717  https://www.hepsiemlak.com/istanbul-sisli-bozk...         12.0
6645  https://www.hepsiemlak.com/eskisehir-tepebasi-...         20.0
2350  https://www.hepsiemlak.com/ankara-sincan-yunus...         48.0
4014  https://www.hepsiemlak.com/gaziantep-sahinbey-...         25.0
4051  https://www.hepsiemlak.com/antalya-konyaalti-h...         28.0
5448  https://www.hepsiemlak.com/ankara-cankaya-kava...         12.0
6672  https://www.hepsiemlak.com/ankara-cankaya-kucu...         22.0
3409  https://www.hepsiemlak.com/denizli-pamukkale-z...         39.0

     list-view-price currency list-view-date                 left  \
7198         110.000       TL     07-07-2025        Kiralık Daire
3726          15.000       TL     28-07-2025        Kiralık Daire
8257          50.000       TL     19-07-2025    Kiralık Residence
4767          21.000       TL     28-07-2025        Kiralık Daire
8961          10.000       TL     29-07-2025        Kiralık Daire
8679          15.000       TL     18-07-2025        Kiralık Daire
5723          15.000       TL     28-07-2025        Kiralık Daire
1139          24.500       TL     30-07-2025        Kiralık Daire
3111          24.500       TL     29-07-2025        Kiralık Daire
1492          80.000       TL     30-07-2025        Kiralık Daire
8651          52.000       TL     02-07-2025        Kiralık Daire
7648          23.000       TL     23-07-2025        Kiralık Daire
5024          32.000       TL     30-07-2025        Kiralık Daire
2356          32.000       TL     27-07-2025        Kiralık Villa
1609          25.000       TL     30-07-2025        Kiralık Daire
5201         110.000       TL     29-07-2025        Kiralık Daire
4437          23.000       TL     25-07-2025        Kiralık Daire
272           27.500       TL     30-07-2025        Kiralık Daire
4621          23.000       TL     24-07-2025        Kiralık Daire
9035          95.000       TL     22-07-2025        Kiralık Daire
4828          45.000       TL     28-07-2025        Kiralık Daire
4612          26.000       TL     29-07-2025        Kiralık Daire
970           18.000       TL     30-07-2025        Kiralık Daire
2249          30.000       TL     29-07-2025        Kiralık Daire
7699          20.000       TL     30-07-2025        Kiralık Daire
7679          11.000       TL     08-07-2025        Kiralık Daire
2285         120.000       TL     28-07-2025        Kiralık Villa
1975          50.000       TL     30-07-2025        Kiralık Daire
8044          25.000       TL     14-07-2025        Kiralık Daire
9318          25.000       TL     24-07-2025        Kiralık Daire
4581          20.750       TL     28-07-2025        Kiralık Daire
2608          22.500       TL     28-07-2025        Kiralık Daire
5848          55.000       TL     29-07-2025        Kiralık Daire
2629          19.000       TL     25-07-2025        Kiralık Daire
3857          24.000       TL     30-07-2025        Kiralık Daire
7238          36.000       TL     10-07-2025        Kiralık Daire
2737          53.000       TL     28-07-2025        Kiralık Daire
8551          20.000       TL     28-07-2025        Kiralık Daire
7696          27.750       TL     30-07-2025        Kiralık Daire
2158          19.000       TL     30-07-2025        Kiralık Daire
6021          18.000       TL     28-07-2025        Kiralık Daire
3137          20.000       TL     30-07-2025  Kiralık Müstakil Ev
8717          38.000       TL     26-07-2025        Kiralık Daire
6645          15.000       TL     29-07-2025        Kiralık Daire
2350          25.000       TL     30-07-2025        Kiralık Daire
4014          16.000       TL     28-07-2025        Kiralık Daire
4051          25.995       TL     26-07-2025        Kiralık Daire
5448          42.000       TL     30-07-2025        Kiralık Daire
6672          30.000       TL     30-07-2025        Kiralık Daire
3409          13.000       TL     30-07-2025        Kiralık Daire

                                   celly celly 2  \
7198  1 +\r\n                          1  113 m²
3726  2 +\r\n                          1   95 m²
8257  3 +\r\n                          1  150 m²
4767  2 +\r\n                          1   75 m²
8961  3 +\r\n                          0  120 m²
8679  2 +\r\n                          1   65 m²
5723  3 +\r\n                          1   75 m²
1139  1 +\r\n                          1   55 m²
3111  2 +\r\n                          1   90 m²
1492  3 +\r\n                          1  140 m²
8651  3 +\r\n                          1  160 m²
7648  1 +\r\n                          1   75 m²
5024  2 +\r\n                          1   59 m²
2356  5 +\r\n                          1  350 m²
1609                              Stüdyo   54 m²
5201  1 +\r\n                          1  130 m²
4437  4 +\r\n                          2  216 m²
272   3 +\r\n                          1  130 m²
4621  2 +\r\n                          1  115 m²
9035  4 +\r\n                          1  240 m²
4828  2 +\r\n                          1  135 m²
4612  2 +\r\n                          1   90 m²
970   1 +\r\n                          1   64 m²
2249  3 +\r\n                          1  155 m²
7699  2 +\r\n                          1   75 m²
7679  1 +\r\n                          1   60 m²
2285  3 +\r\n                          1  150 m²
1975  2 +\r\n                          1  100 m²
8044  3 +\r\n                          1  120 m²
9318  4 +\r\n                          1  185 m²
4581  2 +\r\n                          1   90 m²
2608  4 +\r\n                          1  200 m²
5848  4 +\r\n                          1  210 m²
2629  3 +\r\n                          1  115 m²
3857  1 +\r\n                          1   50 m²
7238  2 +\r\n                          1   85 m²
2737  3 +\r\n                          1  120 m²
8551  3 +\r\n                          1  160 m²
7696  2 +\r\n                          1   95 m²
2158  3 +\r\n                          1  150 m²
6021  2 +\r\n                          1  120 m²
3137  1 +\r\n                          1   65 m²
8717  2 +\r\n                          1   65 m²
6645  1 +\r\n                          1   60 m²
2350  3 +\r\n                          1  114 m²
4014  2 +\r\n                          1   80 m²
4051  1 +\r\n                          1   55 m²
5448  1 +\r\n                          1   50 m²
6672  3 +\r\n                          1  100 m²
3409  2 +\r\n                          1   65 m²

                                    celly 3       celly 4  \
7198   5\r\n                        Yaşında   21 ve üzeri
3726  25\r\n                        Yaşında        2. Kat
8257                             Sıfır Bina        1. Kat
4767  14\r\n                        Yaşında        3. Kat
8961  30\r\n                        Yaşında    En Üst Kat
8679  12\r\n                        Yaşında        1. Kat
5723  25\r\n                        Yaşında        2. Kat
1139                             Sıfır Bina       Ara Kat
3111                             Sıfır Bina       Ara Kat
1492  25\r\n                        Yaşında        7. Kat
8651  30\r\n                        Yaşında         Zemin
7648  27\r\n                        Yaşında         Kot 1
5024   6\r\n                        Yaşında        5. Kat
2356  10\r\n                        Yaşında           NaN
1609   3\r\n                        Yaşında         Zemin
5201   9\r\n                        Yaşında        6. Kat
4437   1\r\n                        Yaşında        2. Kat
272   17\r\n                        Yaşında         Kot 1
4621  18\r\n                        Yaşında        2. Kat
9035  60\r\n                        Yaşında        6. Kat
4828   1\r\n                        Yaşında        5. Kat
4612  10\r\n                        Yaşında        1. Kat
970   16\r\n                        Yaşında        4. Kat
2249   9\r\n                        Yaşında        1. Kat
7699  50\r\n                        Yaşında        2. Kat
7679                             Sıfır Bina        2. Kat
2285  12\r\n                        Yaşında           NaN
1975  45\r\n                        Yaşında    En Üst Kat
8044  30\r\n                        Yaşında       Ara Kat
9318  12\r\n                        Yaşında        3. Kat
4581  31\r\n                        Yaşında    Giriş Katı
2608  11\r\n                        Yaşında        9. Kat
5848                             Sıfır Bina        2. Kat
2629  10\r\n                        Yaşında        5. Kat
3857   5\r\n                        Yaşında  Yüksek Giriş
7238                             Sıfır Bina        1. Kat
2737  14\r\n                        Yaşında        5. Kat
8551  26\r\n                        Yaşında        6. Kat
7696  22\r\n                        Yaşında         Kot 3
2158                             Sıfır Bina        2. Kat
6021  29\r\n                        Yaşında        2. Kat
3137  15\r\n                        Yaşında           NaN
8717  35\r\n                        Yaşında        4. Kat
6645  10\r\n                        Yaşında        1. Kat
2350  21\r\n                        Yaşında        2. Kat
4014   9\r\n                        Yaşında        3. Kat
4051   9\r\n                        Yaşında    Giriş Katı
5448                             Sıfır Bina        4. Kat
6672  50\r\n                        Yaşında        2. Kat
3409   5\r\n                        Yaşında        1. Kat

                                  list-view-location  \
7198              İstanbul / Şişli / Cumhuriyet Mah.
3726               Antalya / Alanya / Mahmutlar Mah.
8257            Aydın / Kuşadası / Değirmendere Mah.
4767                     Aydın / Didim / Efeler Mah.
8961         Eskişehir / Odunpazarı / Gökmeydan Mah.
8679          Balıkesir / Edremit / Cennetayağı Mah.
5723                Ankara / Mamak / Kartaltepe Mah.
1139                Ankara / Gölbaşı / Taşpınar Mah.
3111                    Kocaeli / Darıca / Emek Mah.
1492                Antalya / Konyaaltı / Liman Mah.
8651               İzmir / Karşıyaka / Bostanlı Mah.
7648                 Ankara / Çankaya / Maltepe Mah.
5024               Ankara / Çankaya / Alacaatlı Mah.
2356               Zonguldak / Merkez / İncivez Mah.
1609                       Muğla / Milas / Ören Mah.
5201               İstanbul / Kadıköy / Göztepe Mah.
4437                Bursa / Osmangazi / Panayır Mah.
272                   Ankara / Çankaya / Birlik Mah.
4621                   Ankara / Sincan / Gökçek Mah.
9035                  İstanbul / Şişli / Merkez Mah.
4828           İstanbul / Küçükçekmece / Cennet Mah.
4612                Antalya / Konyaaltı / Hurma Mah.
970                    Mersin / Anamur / İskele Mah.
2249                Aydın / Efeler / Meşrutiyet Mah.
7699          İstanbul / Gaziosmanpaşa / Merkez Mah.
7679          Eskişehir / Odunpazarı / 71 Evler Mah.
2285                     Muğla / Bodrum / Geriş Mah.
1975              İstanbul / Üsküdar / Selimiye Mah.
8044          Ankara / Yenimahalle / Demetevler Mah.
9318                  Konya / Karapınar / Zafer Mah.
4581                   İzmir / Çiğli / Evka - 2 Mah.
2608             Adana / Çukurova / Huzurevleri Mah.
5848             Eskişehir / Odunpazarı / Sümer Mah.
2629               Ankara / Keçiören / Karakaya Mah.
3857                   İzmir / Karşıyaka / Yalı Mah.
7238              Ankara / Çankaya / Naci Çakır Mah.
2737            İstanbul / Beşiktaş / Dikilitaş Mah.
8551                    Mersin / Mezitli / Yeni Mah.
7696     Ankara / Çankaya / Şehit Cengiz Karaca Mah.
2158                 Hatay / Dörtyol / Yeşilköy Mah.
6021              Ankara / Polatlı / Cumhuriyet Mah.
3137                  İzmir / Dikili / Çandarlı Mah.
8717                 İstanbul / Şişli / Bozkurt Mah.
6645  Eskişehir / Tepebaşı / Mustafa Kemal Paşa Mah.
2350               Ankara / Sincan / Yunus Emre Mah.
4014             Gaziantep / Şahinbey / Beştepe Mah.
4051                Antalya / Konyaaltı / Hurma Mah.
5448             Ankara / Çankaya / Kavaklıdere Mah.
6672               Ankara / Çankaya / Küçükesat Mah.
3409            Denizli / Pamukkale / Zeytinköy Mah.

                                           img-wrp href  \
7198                                                NaN
3726                                                NaN
8257  https://www.hepsiemlak.com/emlak-ofisi/jupiter...
4767  https://www.hepsiemlak.com/emlak-ofisi/apollo-...
8961  https://www.hepsiemlak.com/emlak-ofisi/guleryu...
8679                                                NaN
5723  https://www.hepsiemlak.com/emlak-ofisi/anatoli...
1139  https://www.hepsiemlak.com/emlak-ofisi/alacati...
3111  https://www.hepsiemlak.com/emlak-ofisi/vizyon-...
1492  https://www.hepsiemlak.com/emlak-ofisi/turvill...
8651  https://www.hepsiemlak.com/emlak-ofisi/biz-eml...
7648                                                NaN
5024  https://www.hepsiemlak.com/emlak-ofisi/new-yas...
2356                                                NaN
1609                                                NaN
5201  https://www.hepsiemlak.com/emlak-ofisi/remax-a...
4437                                                NaN
272   https://www.hepsiemlak.com/emlak-ofisi/radikal...
4621  https://www.hepsiemlak.com/emlak-ofisi/remax-n...
9035  https://www.hepsiemlak.com/emlak-ofisi/box-rea...
4828                                                NaN
4612  https://www.hepsiemlak.com/emlak-ofisi/turvill...
970                                                 NaN
2249  https://www.hepsiemlak.com/emlak-ofisi/dogru-k...
7699  https://www.hepsiemlak.com/emlak-ofisi/remax-d...
7679  https://www.hepsiemlak.com/emlak-ofisi/clk-gay...
2285                                                NaN
1975  https://www.hepsiemlak.com/emlak-ofisi/yilmaz-...
8044                                                NaN
9318                                                NaN
4581  https://www.hepsiemlak.com/emlak-ofisi/turyap-...
2608  https://www.hepsiemlak.com/emlak-ofisi/lisans-...
5848                                                NaN
2629                                                NaN
3857  https://www.hepsiemlak.com/emlak-ofisi/turpa-g...
7238  https://www.hepsiemlak.com/emlak-ofisi/ersu-ga...
2737                                                NaN
8551  https://www.hepsiemlak.com/emlak-ofisi/han-eml...
7696                                                NaN
2158                                                NaN
6021  https://www.hepsiemlak.com/emlak-ofisi/asiye-e...
3137                                                NaN
8717  https://www.hepsiemlak.com/emlak-ofisi/life-is...
6645                                                NaN
2350                                                NaN
4014                                                NaN
4051  https://www.hepsiemlak.com/emlak-ofisi/konyaal...
5448  https://www.hepsiemlak.com/emlak-ofisi/garden-...
6672  https://www.hepsiemlak.com/emlak-ofisi/oz-de-e...
3409  https://www.hepsiemlak.com/emlak-ofisi/turyap-...

                                      he-lazy-image src    wp-btn  \
7198                                                NaN  Whatsapp
3726                                                NaN  Whatsapp
8257  https://hecdn01.hemlak.com/mncropresize/182/13...  Whatsapp
4767  https://hecdn01.hemlak.com/mncropresize/182/13...  Whatsapp
8961  https://hecdn01.hemlak.com/mncropresize/182/13...  Whatsapp
8679  https://hecdn01.hemlak.com/mncropresize/182/13...  Whatsapp
5723  https://hecdn01.hemlak.com/mncropresize/182/13...  Whatsapp
1139  https://hecdn01.hemlak.com/mncropresize/182/13...  Whatsapp
3111  https://hecdn01.hemlak.com/mncropresize/182/13...  Whatsapp
1492  https://hecdnnw.hemlak.com/mncropresize/77/67/...  Whatsapp
8651  https://hecdn01.hemlak.com/mncropresize/182/13...  Whatsapp
7648  https://hecdn01.hemlak.com/mncropresize/182/13...  Whatsapp
5024  https://hecdn01.hemlak.com/mncropresize/182/13...  Whatsapp
2356  https://hecdn01.hemlak.com/mncropresize/182/13...  Whatsapp
1609  https://hecdn01.hemlak.com/mncropresize/182/13...  Whatsapp
5201  https://hecdn01.hemlak.com/mncropresize/182/13...  Whatsapp
4437  https://hecdn01.hemlak.com/mncropresize/182/13...  Whatsapp
272   https://hecdn01.hemlak.com/mncropresize/182/13...  Whatsapp
4621  https://hecdn01.hemlak.com/mncropresize/182/13...  Whatsapp
9035  https://hecdn01.hemlak.com/mncropresize/182/13...  Whatsapp
4828                                                NaN  Whatsapp
4612  https://hecdnnw.hemlak.com/mncropresize/77/67/...  Whatsapp
970   https://hecdn01.hemlak.com/mncropresize/182/13...  Whatsapp
2249  https://hecdn01.hemlak.com/mncropresize/182/13...  Whatsapp
7699  https://hecdn01.hemlak.com/mncropresize/182/13...  Whatsapp
7679  https://hecdn01.hemlak.com/mncropresize/182/13...  Whatsapp
2285  https://hecdn01.hemlak.com/mncropresize/182/13...  Whatsapp
1975  https://hecdn01.hemlak.com/mncropresize/182/13...  Whatsapp
8044  https://hecdn01.hemlak.com/mncropresize/182/13...  Whatsapp
9318  https://hecdn01.hemlak.com/mncropresize/182/13...  Whatsapp

In [13]:
dir(df) # df ile ilgili fonksiyonları listeler

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__arrow_c_stream__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__dataframe__',
 '__dataframe_consortium_standard__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__firstlineno__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pandas_priority__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__static_attributes__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_agg_examples_doc',
 '_agg_see_also_doc',
 '_align_for_op',
 '_align_frame',
 '_align_series',
 '_append',
 '_arith_method',
 '_arith_method_with_reindex',
 '_as_manager',
 '_attrs',
 '_box_col_values',
 '_can_fast_transpose',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_is_chained_assignment_possible',
 '_check_label_or_level_ambiguity',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_combine_frame',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_result',
 '_constructor',
 '_constructor_from_mgr',
 '_constructor_sliced',
 '_constructor_sliced_from_mgr',
 '_create_data_for_split_and_tight_to_dict',
 '_data',
 '_deprecate_downcast',
 '_dir_additions',
 '_dir_deletions',
 '_dispatch_frame_op',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_ensure_valid_index',
 '_find_valid_index',
 '_flags',
 '_flex_arith_method',
 '_flex_cmp_method',
 '_from_arrays',
 '_from_mgr',
 '_get_agg_axis',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cleaned_column_resolvers',
 '_get_column_array',
 '_get_index_resolvers',
 '_get_item_cache',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_get_values_for_csv',
 '_getitem_bool_array',
 '_getitem_multilevel',
 '_getitem_nocopy',
 '_getitem_slice',
 '_gotitem',
 '_hidden_attrs',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_info_repr',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_copy',
 '_is_homogeneous_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_is_view',
 '_is_view_after_cow_rules',
 '_iset_item',
 '_iset_item_mgr',
 '_iset_not_inplace',
 '_item_cache',
 '_iter_column_arrays',
 '_ixs',
 '_logical_func',
 '_logical_method',
 '_maybe_align_series_as_frame',
 '_maybe_cache_changed',
 '_maybe_update_cacher',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_needs_reindex_multi',
 '_pad_or_backfill',
 '_protect_consolidate',
 '_reduce',
 '_reduce_axis1',
 '_reindex_axes',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_rename',
 '_replace_columnwise',
 '_repr_data_resource_',
 '_repr_fits_horizontal_',
 '_repr_fits_vertical_',
 '_repr_html_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_sanitize_column',
 '_series',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_is_copy',
 '_set_item',
 '_set_item_frame_value',
 '_set_item_mgr',
 '_set_value',
 '_setitem_array',
 '_setitem_frame',
 '_setitem_slice',
 '_shift_with_freq',
 '_should_reindex_frame_op',
 '_slice',
 '_stat_function',
 '_stat_function_ddof',
 '_take_with_is_copy',
 '_to_dict_of_blocks',
 '_to_latex_via_styler',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'apply',
 'applymap',
 'asfreq',
 'asof',
 'assign',
 'astype',
 'at',
 'at_time',
 'attrs',
 'axes',
 'backfill',
 'between_time',
 'bfill',
 'bool',
 'boxplot',
 'celly',
 'clip',
 'columns',
 'combine',
 'combine_first',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'corrwith',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'currency',
 'describe',
 'diff',
 'div',
 'divide',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'eval',
 'ewm',
 'expanding',
 'explode',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'flags',
 'floordiv',
 'from_dict',
 'from_records',
 'ge',
 'get',
 'groupby',
 'gt',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'insert',
 'interpolate',
 'isetitem',
 'isin',
 'isna',
 'isnull',
 'items',
 'iterrows',
 'itertuples',
 'join',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'left',
 'loc',
 'lt',
 'map',
 'mask',
 'max',
 'mean',
 'median',
 'melt',
 'memory_usage',
 'merge',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pad',
 'pct_change',
 'pipe',
 'pivot',
 'pivot_table',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'query',
 'radd',
 'rank',
 'rdiv',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'select_dtypes',
 'sem',
 'set_axis',
 'set_flags',
 'set_index',
 'shape',
 'shift',
 'size',
 'skew',
 'sort_index',
 'sort_values',
 'squeeze',
 'stack',
 'std',
 'style',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_gbq',
 'to_hdf',
 'to_html',
 'to_json',
 'to_latex',
 'to_markdown',
 'to_numpy',
 'to_orc',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'to_xml',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'where',
 'xs']

In [14]:
help(df.drop) # df.drop fonksiyonunun ne işe yaradığını öğreniriz

Help on method drop in module pandas.core.frame:

drop(
    labels: 'IndexLabel | None' = None,
    *,
    axis: 'Axis' = 0,
    index: 'IndexLabel | None' = None,
    columns: 'IndexLabel | None' = None,
    level: 'Level | None' = None,
    inplace: 'bool' = False,
    errors: 'IgnoreRaise' = 'raise'
) -> 'DataFrame | None' method of pandas.core.frame.DataFrame instance
    Drop specified labels from rows or columns.

    Remove rows or columns by specifying label names and corresponding
    axis, or by directly specifying index or column names. When using a
    multi-index, labels on different levels can be removed by specifying
    the level. See the :ref:`user guide <advanced.shown_levels>`
    for more information about the now unused levels.

    Parameters
    ----------
    labels : single label or list-like
        Index or column labels to drop. A tuple will be used as a single
        label and not treated as a list-like.
    axis : {0 or 'index', 1 or 'columns'}, default 0
        Whether to drop labels from the index (0 or 'index') or
        columns (1 or 'columns').
    index : single label or list-like
        Alternative to specifying axis (``labels, axis=0``
        is equivalent to ``index=labels``).
    columns : single label or list-like
        Alternative to specifying axis (``labels, axis=1``
        is equivalent to ``columns=labels``).
    level : int or level name, optional
        For MultiIndex, level from which the labels will be removed.
    inplace : bool, default False
        If False, return a copy. Otherwise, do operation
        in place and return None.
    errors : {'ignore', 'raise'}, default 'raise'
        If 'ignore', suppress error and only existing labels are
        dropped.

    Returns
    -------
    DataFrame or None
        Returns DataFrame or None DataFrame with the specified
        index or column labels removed or None if inplace=True.

    Raises
    ------
    KeyError
        If any of the labels is not found in the selected axis.

    See Also
    --------
    DataFrame.loc : Label-location based indexer for selection by label.
    DataFrame.dropna : Return DataFrame with labels on given axis omitted
        where (all or any) data are missing.
    DataFrame.drop_duplicates : Return DataFrame with duplicate rows
        removed, optionally only considering certain columns.
    Series.drop : Return Series with specified index labels removed.

    Examples
    --------
    >>> df = pd.DataFrame(np.arange(12).reshape(3, 4),
    ...                   columns=['A', 'B', 'C', 'D'])
    >>> df
       A  B   C   D
    0  0  1   2   3
    1  4  5   6   7
    2  8  9  10  11

    Drop columns

    >>> df.drop(['B', 'C'], axis=1)
       A   D
    0  0   3
    1  4   7
    2  8  11

    >>> df.drop(columns=['B', 'C'])
       A   D
    0  0   3
    1  4   7
    2  8  11

    Drop a row by index

    >>> df.drop([0, 1])
       A  B   C   D
    2  8  9  10  11

    Drop columns and/or rows of MultiIndex DataFrame

    >>> midx = pd.MultiIndex(levels=[['llama', 'cow', 'falcon'],
    ...                              ['speed', 'weight', 'length']],
    ...                      codes=[[0, 0, 0, 1, 1, 1, 2, 2, 2],
    ...                             [0, 1, 2, 0, 1, 2, 0, 1, 2]])
    >>> df = pd.DataFrame(index=midx, columns=['big', 'small'],
    ...                   data=[[45, 30], [200, 100], [1.5, 1], [30, 20],
    ...                         [250, 150], [1.5, 0.8], [320, 250],
    ...                         [1, 0.8], [0.3, 0.2]])
    >>> df
                    big     small
    llama   speed   45.0    30.0
            weight  200.0   100.0
            length  1.5     1.0
    cow     speed   30.0    20.0
            weight  250.0   150.0
            length  1.5     0.8
    falcon  speed   320.0   250.0
            weight  1.0     0.8
            length  0.3     0.2

    Drop a specific index combination from the MultiIndex
    DataFrame, i.e., drop the combination ``'falcon'`` and
    ``'weight'``, which deletes only the corresponding row

    >>> df.drop(index=('falcon', 'weight'))
                    big     small
    llama   speed   45.0    30.0
            weight  200.0   100.0
            length  1.5     1.0
    cow     speed   30.0    20.0
            weight  250.0   150.0
            length  1.5     0.8
    falcon  speed   320.0   250.0
            length  0.3     0.2

    >>> df.drop(index='cow', columns='small')
                    big
    llama   speed   45.0
            weight  200.0
            length  1.5
    falcon  speed   320.0
            weight  1.0
            length  0.3

    >>> df.drop(index='length', level=1)
                    big     small
    llama   speed   45.0    30.0
            weight  200.0   100.0
    cow     speed   30.0    20.0
            weight  250.0   150.0
    falcon  speed   320.0   250.0
            weight  1.0     0.8

In [15]:
print(df.columns) # df'nin sütunlarını listeler

Index(['img-link href', 'photo-count', 'list-view-price', 'currency',
       'list-view-date', 'left', 'celly', 'celly 2', 'celly 3', 'celly 4',
       'list-view-location', 'img-wrp href', 'he-lazy-image src', 'wp-btn',
       'listing-card--owner-info__firm-name', 'listing-card--owner-info__name',
       'he-lazy-image src 2', 'list-view-header'],
      dtype='object')

In [16]:
cols = ['photo-count',  'currency','list-view-date', 'left','list-view-location', 'img-wrp href', 'he-lazy-image src', 'wp-btn','listing-card--owner-info__firm-name', 'listing-card--owner-info__name','he-lazy-image src 2', 'list-view-header']
drop_columns(df, cols) # belirtilen sütunları siler

In [17]:
print(df.info())    # df ile ilgili bilgileri tekrar verir, silinen sütunlar artık yoktur

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9452 entries, 0 to 9451
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   img-link href    9452 non-null   object
 1   list-view-price  9452 non-null   object
 2   celly            9452 non-null   object
 3   celly 2          9452 non-null   object
 4   celly 3          9452 non-null   object
 5   celly 4          9070 non-null   object
dtypes: object(6)
memory usage: 443.2+ KB
None

In [18]:
# Örnek bir URL'den sütunları ayırma
# Bu örnek, URL'yi '/' karakterine göre böler ve 3. sütunu alır.
# Bu, genellikle bir web sayfasının belirli bir bölümünü veya öğesini temsil eder.
s = "https://www.hepsiemlak.com/ankara-mamak-general-zeki-dogan-kiralik/daire/159186-7 "
x = s.split('/')[3] # sütunları / ile ayırır
print(x) # 3. sütunu yazdırır

ankara-mamak-general-zeki-dogan-kiralik

In [19]:
# Yeni bir sütun ekleme
df ['location'] = df['img-link href'].apply(lambda x: x.split('/')[3]) # img-link href sütununu / ile ayırır ve 3. sütunu alır
df.info() # df ile ilgili bilgileri tekrar verir, yeni sütun eklenmiştir
df['city'] = df['location'].str.split('-').str[0] # location sütununu - ile ayırır ve 0. sütunu alır
df['district'] = df['location'].str.split('-').str[1] # location sütununu - ile ayırır ve 1. sütunu alır
df['neighborhood'] = df['location'].str.split('-').str[2:-1] # location sütununu - ile ayırır ve 2. sütundan sonrasını alır
df['neighborhood'] = df['neighborhood'].apply(lambda x: '_'.join(x)) # neighborhood sütununu birleştirir
print(df[['city', 'district', 'neighborhood']]) # yeni sütunları gösterir

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9452 entries, 0 to 9451
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   img-link href    9452 non-null   object
 1   list-view-price  9452 non-null   object
 2   celly            9452 non-null   object
 3   celly 2          9452 non-null   object
 4   celly 3          9452 non-null   object
 5   celly 4          9070 non-null   object
 6   location         9452 non-null   object
dtypes: object(7)
memory usage: 517.0+ KB
           city      district        neighborhood
0        ankara         mamak  general_zeki_dogan
1      istanbul    beylikduzu          cumhuriyet
2       antalya         kepez              selale
3      istanbul  kucukcekmece          cumhuriyet
4        ankara      altindag       aydinlikevler
...         ...           ...                 ...
9447     mersin        tarsus        sehitmustafa
9448  gaziantep      sahinbey        bahcelievler
9449      adana        seyhan         namik_kemal
9450      izmir        dikili           ismetpasa
9451      konya        eregli            orhaniye

[9452 rows x 3 columns]

In [20]:
drop_columns(df, ['location','img-link href']) # belirtilen sütunları siler
df.info() # df ile ilgili bilgileri tekrar verir, yeni sütunlar silinmiştir
print(df[['city','district','neighborhood']]) # benzersiz şehirleri listeler

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9452 entries, 0 to 9451
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   list-view-price  9452 non-null   object
 1   celly            9452 non-null   object
 2   celly 2          9452 non-null   object
 3   celly 3          9452 non-null   object
 4   celly 4          9070 non-null   object
 5   city             9452 non-null   object
 6   district         9452 non-null   object
 7   neighborhood     9452 non-null   object
dtypes: object(8)
memory usage: 590.9+ KB
           city      district        neighborhood
0        ankara         mamak  general_zeki_dogan
1      istanbul    beylikduzu          cumhuriyet
2       antalya         kepez              selale
3      istanbul  kucukcekmece          cumhuriyet
4        ankara      altindag       aydinlikevler
...         ...           ...                 ...
9447     mersin        tarsus        sehitmustafa
9448  gaziantep      sahinbey        bahcelievler
9449      adana        seyhan         namik_kemal
9450      izmir        dikili           ismetpasa
9451      konya        eregli            orhaniye

[9452 rows x 3 columns]

In [23]:
print(df.columns)
print(df['celly'].unique()) # benzersiz sütunları listeler

Index(['list-view-price', 'celly', 'celly 2', 'celly 3', 'celly 4', 'city',
       'district', 'neighborhood'],
      dtype='object')
['2 +\r\n                          1' '1 +\r\n                          1'
 '3 +\r\n                          1' '4 +\r\n                          1'
 '5 +\r\n                          1' 'Stüdyo'
 '2 +\r\n                          0' '4 +\r\n                          2'
 '3 +\r\n                          0' '6 +\r\n                          2'
 '7 +\r\n                          2' '7 +\r\n                          1'
 '6 +\r\n                          1'
 '10 +\r\n                          1'
 '4 +\r\n                          0' '3 +\r\n                          2'
 '5 +\r\n                          2' '2 +\r\n                          2'
 '1 +\r\n                          10'
 '4 +\r\n                          3'
 '2 +\r\n                          10'
 '5 +\r\n                          0' '1 +\r\n                          2'
 '3 +\r\n                          10'
 '3 +\r\n                          3'
 '4 +\r\n                          10'
 '1 +\r\n                          3'
 '17 +\r\n                          1'
 '3 +\r\n                          4'
 '1 +\r\n                          11'
 '4 +\r\n                          4' '9 +\r\n                          2'
 '1 +\r\n                          5'
 '11 +\r\n                          1'
 '6 +\r\n                          4' '7 +\r\n                          3'
 '111 +\r\n                          0']

In [26]:
df['celly'] = df['celly'].apply(lambda x: x.replace('Stüdyo', '1+0')) # 'celly' sütunundaki 'Stüdyo' kelimesini '1+0' ile değiştirir
df['celly'] = df['celly'].apply(lambda x: x.replace('\n', '')) # 'celly' sütunundaki '\n' karakterini boşluk ile değiştirir
df['room'] = df['celly'].apply(lambda x: x.split('+')[0]).astype(int) # 'celly' sütununu '+' ile ayırır ve 0. sütunu alır, int tipine çevirir
df['livingroom'] = df['celly'].apply(lambda x: x.split('+')[1]).astype(int) # 'celly' sütununu '+' ile ayırır ve 1. sütunu alır, int tipine çevirir
print(df['room'].unique()) # benzersiz oda sayılarını listeler
print(df['livingroom'].unique()) # benzersiz salon sayılarını listeler
drop_columns(df, ['celly']) # 'celly' sütununu siler
df.info() # df ile ilgili bilgileri tekrar verir, 'celly' sütunu artık yoktur

[  2   1   3   4   5   6   7  10  17   9  11 111]
[ 1  0  2 10  3  4 11  5]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9452 entries, 0 to 9451
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   list-view-price  9452 non-null   object
 1   celly 2          9452 non-null   object
 2   celly 3          9452 non-null   object
 3   celly 4          9070 non-null   object
 4   city             9452 non-null   object
 5   district         9452 non-null   object
 6   neighborhood     9452 non-null   object
 7   room             9452 non-null   int64
 8   livingroom       9452 non-null   int64
dtypes: int64(2), object(7)
memory usage: 664.7+ KB

In [28]:
print(df['celly 2'].unique()) # 'celly 2' sütunundaki benzersiz değerleri listeler

['100 m²' '80 m²' '135 m²' '130 m²' '60 m²' '120 m²' '110 m²' '105 m²'
 '380 m²' '50 m²' '85 m²' '115 m²' '90 m²' '160 m²' '55 m²' '125 m²'
 '65 m²' '200 m²' '43 m²' '400 m²' '75 m²' '145 m²' '25 m²' '165 m²'
 '117 m²' '350 m²' '154 m²' '300 m²' '144 m²' '210 m²' '240 m²' '179 m²'
 '250 m²' '116 m²' '70 m²' '45 m²' '170 m²' '95 m²' '48 m²' '150 m²'
 '174 m²' '62 m²' '155 m²' '140 m²' '72 m²' '187 m²' '220 m²' '355 m²'
 '88 m²' '109 m²' '96 m²' '370 m²' '185 m²' '500 m²' '450 m²' '216 m²'
 '270 m²' '178 m²' '169 m²' '56 m²' '230 m²' '52 m²' '369 m²' '180 m²'
 '600 m²' '156 m²' '164 m²' '290 m²' '366 m²' '282 m²' '234 m²' '106 m²'
 '87 m²' '221 m²' '335 m²' '68 m²' '66 m²' '119 m²' '102 m²' '206 m²'
 '211 m²' '550 m²' '265 m²' '69 m²' '176 m²' '195 m²' '21 m²' '142 m²'
 '700 m²' '47 m²' '124 m²' '190 m²' '280 m²' '225 m²' '137 m²' '89 m²'
 '134 m²' '53 m²' '196 m²' '40 m²' '215 m²' '107 m²' '175 m²' '74 m²'
 '112 m²' '42 m²' '79 m²' '205 m²' '98 m²' '139 m²' '84 m²' '1.001 m²'
 '51 m²' '128 m²' '108 m²' '138 m²' '132 m²' '129 m²' '118 m²' '490 m²'
 '148 m²' '260 m²' '143 m²' '323 m²' '59 m²' '64 m²' '182 m²' '158 m²'
 '82 m²' '41 m²' '750 m²' '77 m²' '204 m²' '67 m²' '219 m²' '152 m²'
 '330 m²' '86 m²' '91 m²' '198 m²' '36 m²' '92 m²' '298 m²' '189 m²'
 '99 m²' '161 m²' '146 m²' '83 m²' '49 m²' '54 m²' '177 m²' '104 m²'
 '101 m²' '94 m²' '320 m²' '97 m²' '111 m²' '15 m²' '71 m²' '20 m²'
 '136 m²' '76 m²' '57 m²' '167 m²' '236 m²' '275 m²' '78 m²' '30 m²'
 '183 m²' '58 m²' '73 m²' '113 m²' '295 m²' '245 m²' '131 m²' '149 m²'
 '63 m²' '35 m²' '162 m²' '126 m²' '760 m²' '27 m²' '123 m²' '186 m²'
 '114 m²' '253 m²' '229 m²' '2.000 m²' '411 m²' '248 m²' '122 m²' '224 m²'
 '133 m²' '299 m²' '163 m²' '93 m²' '147 m²' '46 m²' '259 m²' '455 m²'
 '193 m²' '184 m²' '235 m²' '81 m²' '520 m²' '405 m²' '325 m²' '360 m²'
 '157 m²' '420 m²' '22 m²' '286 m²' '168 m²' '279 m²' '188 m²' '127 m²'
 '44 m²' '141 m²' '208 m²' '226 m²' '1.200 m²' '191 m²' '103 m²'
 '1.288 m²' '244 m²' '375 m²' '310 m²' '340 m²' '38 m²' '650 m²' '159 m²'
 '470 m²' '171 m²' '284 m²' '217 m²' '398 m²' '194 m²' '319 m²' '255 m²'
 '39 m²' '258 m²' '32 m²' '121 m²' '192 m²' '34 m²' '222 m²' '359 m²'
 '365 m²' '243 m²' '730 m²' '256 m²' '484 m²' '498 m²' '153 m²' '480 m²'
 '950 m²' '166 m²' '61 m²' '408 m²' '252 m²' '395 m²' '404 m²' '307 m²'
 '276 m²' '1.400 m²' '1.000 m²' '18 m²' '201 m²' '278 m²' '151 m²' '37 m²'
 '1.452 m²']

In [29]:
df['celly 2'] = df['celly 2'].apply(lambda x: x.replace('.', '')) # 'celly 2' sütunundaki '.' karakterini boşluk ile değiştirir
df['area'] = df['celly 2'].apply(lambda x: x.split(' ')[0]).astype(int) # 'celly 2' sütununu ' ' ile ayırır ve 0. sütunu alır, int tipine çevirir

In [30]:
print(df['area'].unique())

[ 100   80  135  130   60  120  110  105  380   50   85  115   90  160
   55  125   65  200   43  400   75  145   25  165  117  350  154  300
  144  210  240  179  250  116   70   45  170   95   48  150  174   62
  155  140   72  187  220  355   88  109   96  370  185  500  450  216
  270  178  169   56  230   52  369  180  600  156  164  290  366  282
  234  106   87  221  335   68   66  119  102  206  211  550  265   69
  176  195   21  142  700   47  124  190  280  225  137   89  134   53
  196   40  215  107  175   74  112   42   79  205   98  139   84 1001
   51  128  108  138  132  129  118  490  148  260  143  323   59   64
  182  158   82   41  750   77  204   67  219  152  330   86   91  198
   36   92  298  189   99  161  146   83   49   54  177  104  101   94
  320   97  111   15   71   20  136   76   57  167  236  275   78   30
  183   58   73  113  295  245  131  149   63   35  162  126  760   27
  123  186  114  253  229 2000  411  248  122  224  133  299  163   93
  147   46  259  455  193  184  235   81  520  405  325  360  157  420
   22  286  168  279  188  127   44  141  208  226 1200  191  103 1288
  244  375  310  340   38  650  159  470  171  284  217  398  194  319
  255   39  258   32  121  192   34  222  359  365  243  730  256  484
  498  153  480  950  166   61  408  252  395  404  307  276 1400 1000
   18  201  278  151   37 1452]

In [32]:
drop_columns(df, ['celly 2']) # 'celly 2' sütununu siler
df.info() # df ile ilgili bilgileri tekrar verir, 'celly 2' sütunu artık yoktur

Hata: "['celly 2'] not found in axis"
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9452 entries, 0 to 9451
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   list-view-price  9452 non-null   object
 1   celly 3          9452 non-null   object
 2   celly 4          9070 non-null   object
 3   city             9452 non-null   object
 4   district         9452 non-null   object
 5   neighborhood     9452 non-null   object
 6   room             9452 non-null   int64
 7   livingroom       9452 non-null   int64
 8   area             9452 non-null   int64
dtypes: int64(3), object(6)
memory usage: 664.7+ KB

In [33]:
print(df['celly 3'].unique())

['25\r\n                        Yaşında' 'Sıfır Bina'
 '1\r\n                        Yaşında'
 '4\r\n                        Yaşında'
 '40\r\n                        Yaşında'
 '5\r\n                        Yaşında'
 '30\r\n                        Yaşında'
 '10\r\n                        Yaşında'
 '6\r\n                        Yaşında'
 '14\r\n                        Yaşında'
 '35\r\n                        Yaşında'
 '26\r\n                        Yaşında'
 '21\r\n                        Yaşında'
 '3\r\n                        Yaşında'
 '8\r\n                        Yaşında'
 '27\r\n                        Yaşında'
 '29\r\n                        Yaşında'
 '15\r\n                        Yaşında'
 '31\r\n                        Yaşında'
 '20\r\n                        Yaşında'
 '50\r\n                        Yaşında'
 '9\r\n                        Yaşında'
 '7\r\n                        Yaşında'
 '12\r\n                        Yaşında'
 '22\r\n                        Yaşında'
 '13\r\n                        Yaşında'
 '24\r\n                        Yaşında'
 '2\r\n                        Yaşında'
 '45\r\n                        Yaşında'
 '23\r\n                        Yaşında'
 '36\r\n                        Yaşında'
 '38\r\n                        Yaşında'
 '28\r\n                        Yaşında'
 '33\r\n                        Yaşında'
 '32\r\n                        Yaşında'
 '16\r\n                        Yaşında'
 '90\r\n                        Yaşında'
 '11\r\n                        Yaşında'
 '52\r\n                        Yaşında'
 '18\r\n                        Yaşında'
 '17\r\n                        Yaşında'
 '19\r\n                        Yaşında'
 '55\r\n                        Yaşında'
 '34\r\n                        Yaşında'
 '39\r\n                        Yaşında'
 '42\r\n                        Yaşında'
 '44\r\n                        Yaşında'
 '37\r\n                        Yaşında'
 '41\r\n                        Yaşında'
 '250\r\n                        Yaşında'
 '60\r\n                        Yaşında'
 '47\r\n                        Yaşında'
 '43\r\n                        Yaşında'
 '48\r\n                        Yaşında'
 '454\r\n                        Yaşında'
 '51\r\n                        Yaşında'
 '46\r\n                        Yaşında'
 '65\r\n                        Yaşında'
 '100\r\n                        Yaşında'
 '53\r\n                        Yaşında'
 '49\r\n                        Yaşında'
 '70\r\n                        Yaşında'
 '64\r\n                        Yaşında'
 '66\r\n                        Yaşında'
 '80\r\n                        Yaşında'
 '135\r\n                        Yaşında'
 '120\r\n                        Yaşında'
 '95\r\n                        Yaşında'
 '200\r\n                        Yaşında'
 '97\r\n                        Yaşında']

In [34]:
df['celly 3'] = df['celly 3'].apply(lambda x: x.replace('Sıfır Bina', '0')) # 'celly 3' sütunundaki 'Sıfır Bina' kelimesini '0' ile değiştirir
df['celly 3'] = df['celly 3'].apply(lambda x: x.replace('\n', '')) # 'celly 3' sütunundaki '\n' karakterini boşluk ile değiştirir
df['age'] = df['celly 3'].apply(lambda x: x.split(' ')[0]).astype(int) # 'celly 3' sütununu ' ' ile ayırır ve 0. sütunu alır, int tipine çevirir
print(df['age'].unique()) # benzersiz yaşları listeler

[ 25   0   1   4  40   5  30  10   6  14  35  26  21   3   8  27  29  15
  31  20  50   9   7  12  22  13  24   2  45  23  36  38  28  33  32  16
  90  11  52  18  17  19  55  34  39  42  44  37  41 250  60  47  43  48
 454  51  46  65 100  53  49  70  64  66  80 135 120  95 200  97]

In [35]:
drop_columns(df, ['celly 3']) # 'celly 3' sütununu siler
print(df.info()) # df ile ilgili bilgileri tekrar verir, 'celly 3' sütunu artık yoktur

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9452 entries, 0 to 9451
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   list-view-price  9452 non-null   object
 1   celly 4          9070 non-null   object
 2   city             9452 non-null   object
 3   district         9452 non-null   object
 4   neighborhood     9452 non-null   object
 5   room             9452 non-null   int64
 6   livingroom       9452 non-null   int64
 7   area             9452 non-null   int64
 8   age              9452 non-null   int64
dtypes: int64(4), object(5)
memory usage: 664.7+ KB
None

In [36]:
print(df['celly 4'].unique())

['Yüksek Giriş' '8. Kat' '10. Kat' '3. Kat' 'Bahçe Katı' '2. Kat' '4. Kat'
 'Giriş Katı' 'Ara Kat' '1. Kat' 'Zemin' '11. Kat' nan 'Kot 1' '6. Kat'
 'Yarı Bodrum' '9. Kat' 'En Üst Kat' '5. Kat' 'Kot 3' '7. Kat'
 'Teras Katı' '21 ve üzeri' '17. Kat' '20. Kat' '13. Kat' 'Kot 2'
 '15. Kat' 'Villa Katı' 'Çatı Katı' '14. Kat' '12. Kat' '18. Kat' 'Bodrum'
 '19. Kat' 'Bodrum ve Zemin' 'Tripleks' '16. Kat']

In [56]:
'''search_for = [
    'Kot 2',
    'Kot 1'
    ] 
replace_with = [
    '-2. Kat', 
    '-1. Kat'
    ] # arama ve değiştirme işlemleri için kullanılacak değerler'''
replace_dict = {
    'Kot 2': '-2. Kat',
    'Kot 1': '-1. Kat',
    'Kot 3': '-3. Kat',
    'Yüksek Giriş': '1. Kat',
    'Giriş Katı': '1. Kat',
    'Ara Kat': '3. Kat',
    'Zemin': '0. Kat',
    'En Üst Kat': '5. Kat',
    'Bahçe Katı': '0. Kat',
    'Yarı Bodrum': '0. Kat',
    'Teras Katı': '5. Kat',
    '21 ve üzeri': '21. Kat',
    'Çatı Katı': '5. Kat',
    'Villa Katı': '5. Kat',
    'Bodrum': '0. Kat',
    'Bodrum ve Zemin': '0. Kat',
    'Tripleks': '3. Kat',
    'nan': '2. Kat',
} # arama ve değiştirme işlemleri için kullanılacak değerler
df['celly 4'] = df['celly 4'].replace(list(replace_dict.keys()), list(replace_dict.values())).astype(str) # 'celly 4' sütunundaki değerleri replace_dict ile değiştirir, str tipine çevirir
df['floor'] = df['celly 4'].apply(lambda x: x.split('.')[0]).astype(int)# 'celly 4' sütununu ' ' ile ayırır ve 0. sütunu alır

In [59]:
print(df['floor'].unique()) # benzersiz kat sayılarını listeler
drop_columns(df, ['celly 4']) # 'celly 4' sütununu siler
print(df.info()) # df ile ilgili bilgileri tekrar verir, 'celly 4' sütunu artık yoktur

[ 1  8 10  3  0  2  4 11 -1  6  9  5 -3  7 21 17 20 13 -2 15 14 12 18 19
 16]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9452 entries, 0 to 9451
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   list-view-price  9452 non-null   object
 1   city             9452 non-null   object
 2   district         9452 non-null   object
 3   neighborhood     9452 non-null   object
 4   room             9452 non-null   int64
 5   livingroom       9452 non-null   int64
 6   area             9452 non-null   int64
 7   age              9452 non-null   int64
 8   floor            9452 non-null   int64
dtypes: int64(5), object(4)
memory usage: 664.7+ KB
None

In [61]:
print(df['list-view-price'].unique()) # benzersiz fiyatları listeler

['20.000' '29.250' '50.000' '30.000' '32.500' '29.750' '24.000' '18.000'
 '35.000' '15.000' '21.500' '33.000' '47.000' '40.000' '10.000' '25.500'
 '125.000' '75.000' '19.000' '32.000' '24.500' '38.000' '22.000' '25.000'
 '45.000' '18.999' '39.500' '64.000' '250.000' '29.000' '118.000' '14.000'
 '110.000' '175.000' '210.000' '120.000' '58.000' '21.000' '37.500'
 '16.000' '17.500' '18.500' '39.000' '23.000' '55.000' '65.000' '36.000'
 '52.000' '27.000' '37.000' '28.000' '19.500' '35.500' '9.000' '53.000'
 '13.000' '8.500' '90.000' '24.750' '12.500' '11.000' '7.500' '70.000'
 '500.000' '100.000' '122.000' '550.000' '195.000' '190.000' '160.000'
 '94.000' '44.000' '80.000' '12.000' '23.500' '27.500' '60.000' '32.250'
 '170.000' '49.500' '27.950' '200.000' '185.000' '62.000' '300.000'
 '370.000' '400.000' '270.000' '580.000' '450.000' '315.000' '435.000'
 '325.000' '385.000' '42.000' '17.000' '14.500' '26.000' '240.000'
 '62.500' '34.500' '39.250' '31.000' '24.400' '51.000' '19.900' '350.000'
 '36.500' '20.250' '67.500' '230.000' '20.500' '150.000' '16.500'
 '145.000' '72.000' '14.750' '57.000' '13.500' '9.500' '149.000' '34.000'
 '14.250' '22.500' '600.000' '26.500' '7.000' '85.000' '15.500' '41.000'
 '28.500' '43.000' '52.500' '25.900' '15.750' '11.250' '11.500' '11.900'
 '54.000' '225.000' '480.000' '130.000' '198.000' '95.000' '41.750'
 '10.500' '30.500' '41.500' '98.000' '93.000' '380.000' '57.500' '19.999'
 '31.500' '1.200' '10.250' '82.500' '280.000' '180.000' '68.000' '33.500'
 '15.250' '40.500' '48.000' '47.500' '16.750' '36.999' '3.000' '45.250'
 '17.050' '59.000' '46.000' '44.500' '29.500' '165.000' '290.000'
 '750.000' '12.900' '23.950' '2.500' '21.750' '340.000' '42.500' '44.999'
 '1.915.000' '140.000' '20.300' '17.750' '8.000' '360.000' '6.000' '8.750'
 '12.499' '87.000' '15.800' '13.900' '16.850' '155.000' '8.250' '69.000'
 '5.500' '2.100.000' '6.750' '135.000' '78.000' '25.250' '82.000'
 '260.000' '17.850' '121.000' '6.500' '17.500.000' '97.500' '34.900'
 '53.500' '73.000' '47.250' '25.750' '275.000' '49.000' '77.500' '11.750'
 '38.500' '122.500' '19.850' '48.500' '1.200.000' '22.450' '495.000'
 '115.000' '59.500' '9.750' '285.000' '430.000' '103.000' '42.750' '4.000'
 '56.000' '9.999' '22.900' '105.000' '475.000' '19.250' '37.250' '43.500'
 '61.000' '46.500' '55.500' '3.800.000' '40.900' '112.000' '86.000'
 '77.000' '575.000' '920.000' '66.000' '144.000' '19.950' '108.000'
 '390.000' '19.750' '44.750' '24.999' '25.995' '29.950' '22.750' '13.750'
 '159.000' '67.000' '12.750' '28.900' '40.650' '12.749' '9.250' '74.000'
 '21.800' '20.750' '16.900' '81.000' '12.850' '24.900' '31.750' '37.999'
 '10.900' '92.500' '34.950' '11.995' '13.999' '27.750' '18.750' '32.750'
 '84.000' '45.500' '15.499' '15.999' '14.999' '12.250' '8.600' '2.750.000'
 '32.900' '39.750' '850.000' '610.000' '51.500' '11.749' '17.250' '13.250'
 '625' '245.000' '23.900' '15.200' '10.750' '33.750' '15.945' '24.250'
 '63.000' '36.900' '88.000' '43.900' '26.900' '23.150' '40.250' '1.750'
 '15.100' '215.000' '99.000' '128.000' '97.000' '330.000' '24.950'
 '22.250' '35.600' '66.500' '29.900' '63.500' '13.499' '2.000' '9.800'
 '15.550' '415.000' '15.700' '124.000' '26.250' '92.000' '5.990.000'
 '35.750' '1.000.000' '10.999' '650.000' '18.250' '34.750' '295.000'
 '16.350' '17.499' '310.000' '2.950.000' '27.900' '12.999' '79.000'
 '71.000' '14.100' '75.500' '5.000' '44.900' '255.000']

In [63]:
df['list-view-price'] = df['list-view-price'].astype(str).apply(lambda x: x.replace('.', '')) # 'list-view-price' sütununu str tipine çevirir ve '.' karakterini boşluk ile değiştirir
df['price'] = df['list-view-price'].astype(int) # 'list-view-price' sütununu int tipine çevirir ve 'price' sütununa atar

In [64]:
print(df['price'].unique()) # benzersiz kat sayılarını listeler

[   20000    29250    50000    30000    32500    29750    24000    18000
    35000    15000    21500    33000    47000    40000    10000    25500
   125000    75000    19000    32000    24500    38000    22000    25000
    45000    18999    39500    64000   250000    29000   118000    14000
   110000   175000   210000   120000    58000    21000    37500    16000
    17500    18500    39000    23000    55000    65000    36000    52000
    27000    37000    28000    19500    35500     9000    53000    13000
     8500    90000    24750    12500    11000     7500    70000   500000
   100000   122000   550000   195000   190000   160000    94000    44000
    80000    12000    23500    27500    60000    32250   170000    49500
    27950   200000   185000    62000   300000   370000   400000   270000
   580000   450000   315000   435000   325000   385000    42000    17000
    14500    26000   240000    62500    34500    39250    31000    24400
    51000    19900   350000    36500    20250    67500   230000    20500
   150000    16500   145000    72000    14750    57000    13500     9500
   149000    34000    14250    22500   600000    26500     7000    85000
    15500    41000    28500    43000    52500    25900    15750    11250
    11500    11900    54000   225000   480000   130000   198000    95000
    41750    10500    30500    41500    98000    93000   380000    57500
    19999    31500     1200    10250    82500   280000   180000    68000
    33500    15250    40500    48000    47500    16750    36999     3000
    45250    17050    59000    46000    44500    29500   165000   290000
   750000    12900    23950     2500    21750   340000    42500    44999
  1915000   140000    20300    17750     8000   360000     6000     8750
    12499    87000    15800    13900    16850   155000     8250    69000
     5500  2100000     6750   135000    78000    25250    82000   260000
    17850   121000     6500 17500000    97500    34900    53500    73000
    47250    25750   275000    49000    77500    11750    38500   122500
    19850    48500  1200000    22450   495000   115000    59500     9750
   285000   430000   103000    42750     4000    56000     9999    22900
   105000   475000    19250    37250    43500    61000    46500    55500
  3800000    40900   112000    86000    77000   575000   920000    66000
   144000    19950   108000   390000    19750    44750    24999    25995
    29950    22750    13750   159000    67000    12750    28900    40650
    12749     9250    74000    21800    20750    16900    81000    12850
    24900    31750    37999    10900    92500    34950    11995    13999
    27750    18750    32750    84000    45500    15499    15999    14999
    12250     8600  2750000    32900    39750   850000   610000    51500
    11749    17250    13250      625   245000    23900    15200    10750
    33750    15945    24250    63000    36900    88000    43900    26900
    23150    40250     1750    15100   215000    99000   128000    97000
   330000    24950    22250    35600    66500    29900    63500    13499
     2000     9800    15550   415000    15700   124000    26250    92000
  5990000    35750  1000000    10999   650000    18250    34750   295000
    16350    17499   310000  2950000    27900    12999    79000    71000
    14100    75500     5000    44900   255000]

In [65]:
drop_columns(df, ['list-view-price']) # 'list-view-price' sütununu siler
df.info() # df ile ilgili bilgileri tekrar verir, 'list-view-price' sütunu artık yoktur

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9452 entries, 0 to 9451
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   city          9452 non-null   object
 1   district      9452 non-null   object
 2   neighborhood  9452 non-null   object
 3   room          9452 non-null   int64
 4   livingroom    9452 non-null   int64
 5   area          9452 non-null   int64
 6   age           9452 non-null   int64
 7   floor         9452 non-null   int64
 8   price         9452 non-null   int64
dtypes: int64(6), object(3)
memory usage: 664.7+ KB

In [66]:
print(df.info()) # benzersiz kat sayılarını listeler

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9452 entries, 0 to 9451
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   city          9452 non-null   object
 1   district      9452 non-null   object
 2   neighborhood  9452 non-null   object
 3   room          9452 non-null   int64
 4   livingroom    9452 non-null   int64
 5   area          9452 non-null   int64
 6   age           9452 non-null   int64
 7   floor         9452 non-null   int64
 8   price         9452 non-null   int64
dtypes: int64(6), object(3)
memory usage: 664.7+ KB
None

In [67]:
df.to_csv('hepsiemlak_cleaned.csv', index=False) # temizlenmiş veriyi csv dosyasına kaydeder
print("Veri temizleme işlemi tamamlandı ve hepsiemlak_cleaned.csv dosyasına kaydedildi.") # işlem tamamlandığında mesaj verir

Veri temizleme işlemi tamamlandı ve hepsiemlak_cleaned.csv dosyasına kaydedildi.